# Assuming you have intel GPU or iGPU https://jellyfin.org/docs/general/post-install/transcoding/hardware-acceleration/intel
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 0:0
    group_add:
      - "{{ CHANGE ME}}"   # getent group render | cut -d: -f3
    environment:
      - TZ=America/New_York
    volumes:
      - {{ CHANGE ME }}:/config
      - {{ CHANGE ME }}:/data/tvshows
      - {{ CHANGE ME }}:/data/movies
      - {{ CHANGE ME }}:/transcode
    devices:
      - /dev/dri:/dev/dri  # Pass through the Intel iGPU, Remove and replace if you dont have intel GPU
    ports:
      - 8096:8096
    restart: unless-stopped
