---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PUID=1000
      - TZ=America/New_York
    volumes:
      - {{ CHANGE ME }}:/config
      - {{ CHANGE ME }}:/data
    ports:
      - 7878:7878
    restart: unless-stopped
