---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /CHANGE_ME:/config                        # External storage for persistent config
      - /CHANGE_ME:/data                          # Folder with the expected structure https://wiki.servarr.com/docker-guide#Consistent_and_well_planned_paths
    ports:
      - 8989:8989
    restart: unless-stopped
